name: Bug report
description: Report a bug in getunstucked
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Describe the bug clearly.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1) ...
        2) ...
        3) ...
    validations:
      required: true

  - type: input
    attributes:
      label: OS
      placeholder: Windows 11 / macOS / Linux
    validations:
      required: true

  - type: input
    attributes:
      label: App version
      placeholder: v0.x.x or commit hash
