name: Feature request
description: Suggest a new feature
title: "[Feature] "
labels: ["feature"]
body:
  - type: textarea
    attributes:
      label: What problem does this solve?
    validations:
      required: true

  - type: textarea
    attributes:
      label: What should it do?
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Platform
      options:
        - Desktop (Tauri)
        - Web UI
        - Both
